# Generated by Django 5.2.9 on 2025-12-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_file_drive_download_link_file_drive_file_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="drive_folder_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
