# Generated by Django 5.2.9 on 2025-12-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_drive_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="google_drive_token",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
