# Generated by Django 5.2.9 on 2025-12-21 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["company_name"],
                "verbose_name": "Müşteri",
                "verbose_name_plural": "Müşteriler",
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="annual_revenue",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Yıllık Ciro"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_customers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sorumlu Kişi",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Doğum Tarihi"),
        ),
        migrations.AddField(
            model_name="customer",
            name="contract_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Sözleşme Bitiş"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="contract_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Sözleşme Başlangıç"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.CharField(
                blank=True, default="Türkiye", max_length=100, verbose_name="Ülke"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="district",
            field=models.CharField(blank=True, max_length=100, verbose_name="İlçe"),
        ),
        migrations.AddField(
            model_name="customer",
            name="employee_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Çalışan Sayısı"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="facebook",
            field=models.URLField(blank=True, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="customer",
            name="has_ads_service",
            field=models.BooleanField(default=False, verbose_name="Reklam Yönetimi"),
        ),
        migrations.AddField(
            model_name="customer",
            name="has_social_media_service",
            field=models.BooleanField(
                default=False, verbose_name="Sosyal Medya Yönetimi"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="has_web_design_service",
            field=models.BooleanField(default=False, verbose_name="Web Tasarım"),
        ),
        migrations.AddField(
            model_name="customer",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("technology", "Teknoloji"),
                    ("healthcare", "Sağlık"),
                    ("education", "Eğitim"),
                    ("retail", "Perakende"),
                    ("manufacturing", "Üretim"),
                    ("construction", "İnşaat"),
                    ("food", "Gıda"),
                    ("tourism", "Turizm"),
                    ("finance", "Finans"),
                    ("real_estate", "Gayrimenkul"),
                    ("automotive", "Otomotiv"),
                    ("media", "Medya/Reklam"),
                    ("legal", "Hukuk"),
                    ("consulting", "Danışmanlık"),
                    ("other", "Diğer"),
                ],
                max_length=50,
                verbose_name="Sektör Kategorisi",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Instagram"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="linkedin",
            field=models.URLField(blank=True, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="customer",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="customer_logos/", verbose_name="Logo"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="mersis_no",
            field=models.CharField(blank=True, max_length=20, verbose_name="MERSİS No"),
        ),
        migrations.AddField(
            model_name="customer",
            name="monthly_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Aylık Ücret",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_day",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Ödeme Günü"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Posta Kodu"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Düşük"),
                    ("normal", "Normal"),
                    ("high", "Yüksek"),
                    ("vip", "VIP"),
                ],
                default="normal",
                max_length=20,
                verbose_name="Öncelik",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="secondary_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="İkinci Email"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("website", "Web Sitesi"),
                    ("referral", "Referans"),
                    ("social_media", "Sosyal Medya"),
                    ("google_ads", "Google Ads"),
                    ("cold_call", "Soğuk Arama"),
                    ("event", "Etkinlik/Fuar"),
                    ("other", "Diğer"),
                ],
                max_length=50,
                verbose_name="Müşteri Kaynağı",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="tags",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Etiketler"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="title",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ünvan"),
        ),
        migrations.AddField(
            model_name="customer",
            name="trade_registry_no",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Ticaret Sicil No"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="twitter",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Twitter/X"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, verbose_name="Adres"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Şehir"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="company_name",
            field=models.CharField(max_length=255, verbose_name="Firma Adı"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="contact_person",
            field=models.CharField(max_length=255, verbose_name="Yetkili Kişi"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="has_hosting_service",
            field=models.BooleanField(default=False, verbose_name="Hosting Hizmeti"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="has_seo_service",
            field=models.BooleanField(default=False, verbose_name="SEO Hizmeti"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notlar"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="secondary_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="İkinci Telefon"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="sector",
            field=models.CharField(blank=True, max_length=100, verbose_name="Sektör"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Aktif"),
                    ("inactive", "Pasif"),
                    ("suspended", "Askıya Alındı"),
                ],
                default="active",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="tax_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Vergi Numarası"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="tax_office",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Vergi Dairesi"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="website",
            field=models.URLField(blank=True, verbose_name="Web Sitesi"),
        ),
    ]
