# Generated by Django 5.2.9 on 2025-12-20 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("domain_name", models.CharField(max_length=255)),
                ("registrar", models.CharField(max_length=100)),
                ("register_date", models.DateField()),
                ("expire_date", models.DateField()),
                ("auto_renew", models.BooleanField(default=True)),
                ("dns_provider", models.CharField(blank=True, max_length=100)),
                ("nameservers", models.TextField(blank=True)),
                ("ssl_provider", models.CharField(blank=True, max_length=100)),
                ("ssl_expire_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("notify_30_days", models.BooleanField(default=True)),
                ("notify_15_days", models.BooleanField(default=True)),
                ("notify_7_days", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="organization.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="customers.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "domains",
                "ordering": ["expire_date"],
            },
        ),
        migrations.CreateModel(
            name="Hosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=100)),
                ("plan_name", models.CharField(max_length=100)),
                ("server_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("server_location", models.CharField(blank=True, max_length=100)),
                ("disk_space", models.CharField(blank=True, max_length=50)),
                ("bandwidth", models.CharField(blank=True, max_length=50)),
                ("start_date", models.DateField()),
                ("expire_date", models.DateField()),
                (
                    "monthly_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="TRY", max_length=3)),
                ("cpanel_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="organization.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostings",
                        to="customers.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hostings",
                "ordering": ["expire_date"],
            },
        ),
    ]
